# (Du kannst diese Version-Zeile weglassen, wenn du willst – sie ist inzwischen optional)
version: '3'

services:
  app:
    build: .
    container_name: hello-world-app
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: hello-world-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html
    depends_on:
      - app

volumes:
  mongo_data:
