version: '3'
services:
  app:
    build: .
    container_name: hello-world-app
    ports:
      - "3001:3001"
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public_html:/usr/share/nginx/html
